[package]
name = "recmari-core"
version = "0.1.0"
edition = "2021"

[dependencies]
recmari-proto = { path = "../recmari-proto" }
image = "0.25"
imageproc = "0.25"
ab_glyph = "0.2"
anyhow = "1"
thiserror = "2"
tracing = "0.1"
